POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Unite sunmit",
    "detais": "Um evento para quem é apaixonado por programação",
    "maximumAttendees": 180
}

###
POST http://localhost:3333/events/e6c40e49-c7bd-4e3c-a424-246354df6c90/attendees
Content-Type: application/json

{
    "name": "João Guilherme dos Santos",
    "email": "joaoguilhermesantos2909@gmail.com"
}

###
GET http://localhost:3333/events/e6c40e49-c7bd-4e3c-a424-246354df6c90

###
GET http://localhost:3333/attendees/1/badge

###
GET http://localhost:3333/attendees/1/checkin

###
GET http://localhost:3333/events/e6c40e49-c7bd-4e3c-a424-246354df6c90/attendees